version: '3'
services:
  gateway-service:
    build: ./gateway-service
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - microservices-network

  user-service:
    build: ./user-service
    networks:
      - microservices-network

  product-service:
    build: ./product-service
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge