version: '3'

services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    networks:
      - microservice-network

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    networks:
      - microservice-network

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    networks:
      - microservice-network

  gateway-service:
    build: ./gateway-service
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge